[report-converter] Support Markdownlint
Ericsson/codechecker pull request #2829
Opened 2020-07-10 11:15 UTC by csordasmarton

2020-07-10 11:17 UTC, gyorb commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           

Complexity increasing per file
==============================
- tools/report-converter/codechecker_report_converter/markdownlint/analyzer_result.py  2
- tools/report-converter/codechecker_report_converter/markdownlint/output_parser.py  3
- tools/report-converter/tests/unit/test_mdl_parser.py  3
         

Clones added
============
- tools/report-converter/codechecker_report_converter/markdownlint/output_parser.py  2
- tools/report-converter/tests/unit/test_mdl_parser.py  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/CodeChecker/codechecker/pullRequest?prid=5833787&bid=19101450)

2020-08-24 10:01 UTC, bruntib requested changes

2020-08-24 10:01 UTC, bruntib commented on tools/report-converter/codechecker_report_converter/markdownlint/output_parser.py
> +            r'(?P<checker>[\S ]+) '
Does space character need to be included in checker name? Doesn't it capture all words of the checker message eagerly except for the last one?

2020-08-24 13:23 UTC, gyorb commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           

Complexity increasing per file
==============================
- tools/report-converter/codechecker_report_converter/markdownlint/output_parser.py  3
- tools/report-converter/codechecker_report_converter/markdownlint/analyzer_result.py  2
- tools/report-converter/tests/unit/test_mdlint_parser.py  3
         

Clones added
============
- tools/report-converter/codechecker_report_converter/markdownlint/output_parser.py  2
- tools/report-converter/tests/unit/test_mdlint_parser.py  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/CodeChecker/codechecker/pullRequest?prid=5833787&bid=19101450)

2020-08-24 14:11 UTC, gyorb requested changes
There is an extra dot in the store file paths:
~/codechecker/docs**/.**/usage.md

I think it gets there during the report conversion because the parse command prints out that extra dot too in the filepath.

2020-08-24 14:11 UTC, gyorb commented on tools/report-converter/README.md
> +report-converter -t mdlint -o ./codechecker_mdlint_reports ./mdlint_reports.out
```suggestion
report-converter -t mdl -o ./codechecker_mdl_reports ./mdl_reports.out
```

2020-08-24 14:11 UTC, gyorb commented on tools/report-converter/README.md
> +mdl /path/to/your/project > ./mdlint_reports.out
```suggestion
mdl /path/to/your/project > ./mdl_reports.out
```

2020-08-24 14:11 UTC, gyorb commented on tools/report-converter/README.md
> +CodeChecker store ./codechecker_mdlint_reports -n mdlint
```suggestion
CodeChecker store ./codechecker_mdl_reports -n mdl
```

2020-08-24 14:11 UTC, gyorb commented on tools/report-converter/codechecker_report_converter/markdownlint/analyzer_result.py
> +    TOOL_NAME = 'mdlint'
```suggestion
    TOOL_NAME = 'mdl'
```

2020-08-24 14:11 UTC, gyorb commented on tools/report-converter/tests/unit/mdlint_output_test_files/Makefile
> +	mdl ./files/readme.md > readme.out
maybe it is worth to mention here or somewhere in the test documentation that there is a docker file which can be used to install and execute markdownlint easier:
```
docker run --rm -v ${PWD}:/data markdownlint/markdownlint .
```

2020-08-25 07:04 UTC, gyorb commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           

Complexity increasing per file
==============================
- tools/report-converter/tests/unit/test_mdl_parser.py  3
- tools/report-converter/codechecker_report_converter/markdownlint/analyzer_result.py  2
- tools/report-converter/codechecker_report_converter/markdownlint/output_parser.py  3
         

Clones added
============
- tools/report-converter/tests/unit/test_mdl_parser.py  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/CodeChecker/codechecker/pullRequest?prid=5833787&bid=19101450)

2020-08-25 08:14 UTC, bruntib approved these changes

2020-08-31 09:11 UTC, merged