[gui][server] Statistics
Ericsson/codechecker pull request #2897
Opened 2020-08-19 10:49 UTC by csordasmarton

- Show statistics in separate tabs.
- Component statistics.
- Compare statistics.
- Improve compare queries by using subqueries.

2020-08-19 10:51 UTC, gyorb commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
- Added 41
           

Complexity increasing per file
==============================
- web/server/vue-cli/src/components/Statistics/StatisticsHelper.js  3
         

Complexity decreasing per file
==============================
+ web/server/codechecker_server/api/report_server.py  -1
         

Clones removed
==============
+ web/server/codechecker_server/api/report_server.py  -9
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/CodeChecker/codechecker/pullRequest?prid=6038424&bid=19786675)

2020-09-03 16:29 UTC, gyorb requested changes
The default sorting could be based on the severity of the checkers in the component statistics view too.

Also please check travis, the tests did not run.

2020-09-03 16:29 UTC, gyorb commented on web/server/codechecker_server/api/report_server.py
> +def get_outstanding_reports_filter(tbl=Report):
this was renamed to open reports right?

what is the `tbl=Report` expression, Report is a type right?

2020-09-03 16:29 UTC, gyorb commented on web/server/codechecker_server/api/report_server.py
> +    query_a = get_diff_bug_id_query(session, run_ids, base_tag_ids)
could you add a bit more meaningful names to query_a ans query_b, one of them is the base and the other is the new?

2020-09-03 16:29 UTC, gyorb commented on web/server/codechecker_server/api/report_server.py
> +def filter_report_filter(q, filter_expression):
Maybe we should rename this function to something more descriptive and add a docstring about why it is needed.
It just joins the File and ReviewStatus tables and applies the filter expression.

2020-09-03 16:29 UTC, gyorb commented on web/server/codechecker_server/api/report_server.py
> +                .filter(get_outstanding_reports_filter(report_cnt_q.c)) \
open reports filter? Shouldn't the query from the other PR be used when that is merged?

2020-09-04 12:28 UTC, gyorb commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
- Added 41
           

Complexity increasing per file
==============================
- web/server/vue-cli/src/components/Statistics/StatisticsHelper.js  3
         

Complexity decreasing per file
==============================
+ web/server/codechecker_server/api/report_server.py  -1
         

Clones removed
==============
+ web/server/codechecker_server/api/report_server.py  -11
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/CodeChecker/codechecker/pullRequest?prid=6038424&bid=19786675)

2020-09-07 21:36 UTC, gyorb requested changes
please resolve the merge conflict

2020-09-08 13:20 UTC, gyorb commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
- Added 41
           

Complexity increasing per file
==============================
- web/server/vue-cli/src/components/Statistics/StatisticsHelper.js  3
         

Complexity decreasing per file
==============================
+ web/server/codechecker_server/api/report_server.py  -2
         

Clones removed
==============
+ web/server/codechecker_server/api/report_server.py  -11
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/CodeChecker/codechecker/pullRequest?prid=6038424&bid=19786675)

2020-09-08 17:36 UTC, gyorb requested changes
I've tested some use cases and found some interesting behavior.

click on the statistics/component statistics tab and there is let's say 2 confirmed bugs for a component.
click on the number 2
the UI jumps to the reports tab but the reports are not filtered based on the checker name the review status and the source component, I see much more results not just the 2 which were expected.
Is this behavior known and will be resolved in #2913?

2020-09-09 06:53 UTC, csordasmarton commented
@gyorb Yes, this problem will be solved in #2913.

2020-09-09 12:46 UTC, gyorb approved these changes

2020-09-09 12:46 UTC, merged