[gui] Expandable runs
Ericsson/codechecker pull request #2953
Opened 2020-09-25 10:19 UTC by csordasmarton

2020-09-25 10:22 UTC, gyorb commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 51
- Added 77
           

Complexity increasing per file
==============================
- web/server/vue-cli/src/mixins/date.mixin.js  1
- web/server/vue-cli/src/store/modules/run.js  9
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/CodeChecker/codechecker/pullRequest?prid=6236530&bid=20319896)

2020-10-12 07:55 UTC, gyorb commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 51
- Added 78
           

Complexity increasing per file
==============================
- web/server/vue-cli/src/store/modules/run.js  9
- web/server/vue-cli/src/mixins/date.mixin.js  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/CodeChecker/codechecker/pullRequest?prid=6236530&bid=20319896)

2020-10-12 08:19 UTC, csordasmarton commented on web/server/codechecker_server/api/report_server.py
> +            if stored.after:
@bruntib I tried it and the default value will be None if these fields are not set on the client side.

2020-10-12 08:21 UTC, gyorb commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 51
- Added 78
           

Complexity increasing per file
==============================
- web/server/vue-cli/src/mixins/date.mixin.js  1
- web/server/vue-cli/src/store/modules/run.js  9
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/CodeChecker/codechecker/pullRequest?prid=6236530&bid=20319896)

2020-10-12 15:17 UTC, gyorb requested changes
Could you extend the history entries with some text to be more explicit about the numbers there.
So the users are not confused what those numbers mean (successful/failed analysis of the source files).
I think some users could think that those numbers are report numbers.

2020-10-13 08:31 UTC, gyorb commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 51
- Added 78
           

Complexity increasing per file
==============================
- web/server/vue-cli/src/mixins/date.mixin.js  1
- web/server/vue-cli/src/store/modules/run.js  9
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/CodeChecker/codechecker/pullRequest?prid=6236530&bid=20319896)

2020-10-13 08:32 UTC, csordasmarton commented
@gyorb I added a tooltip on these numbers and to this section.

I don't really want to add a string explicitly before the analyzer statistics section. By the way if I check a  run line I can see that these are analysis statistics, so I can expect that here these are also analyzer statistics. But with my changes if I hover my mouse over this it will shows me this information too.

What do you think?

2020-10-16 15:14 UTC, gyorb reviewed
Firefox breaks the tool tip lines a bit weird or is that appear only on my machine?
Like this:
```
Analysis statistics: shows the number of successfully analyzed
files
and the number of files which failed to analyze.
```
Chromium seems to be fine.

Otherwise LGTM.

2020-10-29 13:46 UTC, gyorb commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 51
- Added 128
           

Complexity increasing per file
==============================
- web/server/vue-cli/src/store/modules/run.js  9
- web/server/vue-cli/src/mixins/date.mixin.js  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/CodeChecker/codechecker/pullRequest?prid=6236530&bid=20319896)

2020-10-29 15:12 UTC, gyorb requested changes
a space is missing

2020-10-29 15:12 UTC, gyorb commented on web/server/vue-cli/src/components/Run/AnalyzerStatisticsBtn.vue
> +    :title="'Analysis statistics: shows the number of successfully analyzed' +
```suggestion
    :title="'Analysis statistics: shows the number of successfully analyzed ' +
```

2020-10-30 13:40 UTC, gyorb approved these changes

2020-10-30 13:41 UTC, merged