[gui] Show reports line number only in non unique mode
Ericsson/codechecker pull request #2958
Opened 2020-10-02 08:52 UTC by csordasmarton

In unique mode the line number is not available for reports. This patch
will handle this use case and will not show the Line label beside the
file path in unique mode.

2020-10-12 14:58 UTC, gyorb requested changes
If I click on the uniqueing the column length for the file names are calculated a bit weird. I see this:
![image](https://user-images.githubusercontent.com/10214062/95761059-1455af00-0cac-11eb-876c-4c0fd2d3fb7c.png)

2020-11-09 14:19 UTC, csordasmarton commented
If we do not break the file path it will look like this:
![image](https://user-images.githubusercontent.com/6695818/98552305-9979b700-229e-11eb-8f65-d001571bd2b4.png)

If we break it, the width will be calculated some times in a wrong way. This is a css problem, I don't know a better solution for this problem now.

By the way this problem wasn't introduced in this PR. In this PR I just solve the problem to not showing the column number if it is not available.

2020-11-09 15:03 UTC, gyorb approved these changes

2020-11-09 15:04 UTC, gyorb commented
ok, thanks we can think of a solution later

2020-11-09 15:04 UTC, merged