[gui] Select tag for each run filter item
Ericsson/codechecker pull request #2959
Opened 2020-10-02 12:32 UTC by csordasmarton

Screenshot:
![image](https://user-images.githubusercontent.com/6695818/94923358-03db5280-04bc-11eb-9898-2116260eb26f.png)

2020-10-02 12:35 UTC, gyorb commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
- Added 5
           
```


See the complete overview on [Codacy](https://app.codacy.com/manual/CodeChecker/codechecker/pullRequest?prid=6274362&bid=20421848)

2020-10-12 14:49 UTC, gyorb requested changes
If I have a store event on the 6th of October it is listed if I select some dates after that (7th or 8th ...) was there a discussion to see the history elements around that date (+- 5days) and not just after the selected date?

Another question if I only hover over a run (not select it) and I select a run history event (or tag) than click apply the run will not be selected and the reports will not be filtered based on that,

2020-10-12 14:49 UTC, gyorb commented on web/server/vue-cli/src/components/Report/ReportFilter/Filters/BaselineTagItems.vue
> +              const name = tag.name || "N/A";
What do you think about renaming the `N/A` to something like `Storage without a named tag`
If I have multiple store events without a tag I just see a list of `N/A`.

2020-10-12 14:49 UTC, gyorb commented on web/server/vue-cli/src/components/Report/ReportFilter/Filters/BaselineRunFilter.vue
> +                Use <v-icon>mdi-cog</v-icon> button beside each run after
```suggestion
                Use the <v-icon>mdi-cog</v-icon> button beside each run after
```

2020-10-13 11:34 UTC, gyorb commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
- Added 5
           
```


See the complete overview on [Codacy](https://app.codacy.com/manual/CodeChecker/codechecker/pullRequest?prid=6274362&bid=20421848)

2020-10-13 11:39 UTC, csordasmarton commented
@gyorb Yes, there was a dicussion but are we sure that we want to do that. Most of the time the user would like to find a tag by a date. For example last week Monday. I select the date end it will gives me the tags. The first item will be the latest tag on this date. So most of the time I will select the first item.
If we show the previous 5 tags and the next 5 tags for me it would be hard to find the tag what I am looking for.

2020-11-06 15:14 UTC, gyorb approved these changes

2020-11-06 15:14 UTC, merged