[server] Don't remove reports with the same report hash
Ericsson/codechecker pull request #3000
Opened 2020-11-02 12:59 UTC by csordasmarton

> Closes #2952

Previously the server removed reports from the database which have the same
report hash on run update. With this patch we will not remove these reports
but we will set the detection status to Resolved.

2020-11-06 14:28 UTC, gyorb requested changes

2020-11-06 14:28 UTC, gyorb commented on web/tests/functional/db_cleanup/test_db_cleanup.py
> +        self.assertNotEqual(
Why was the source file garbage collection behavior modified here?
If some source file was modified those source files should be removed and new source files should be added stored to that report?
Shouldn't be that tested here? However the test function name doesn't say much `test_garbage_file_collection`.
Should we check if the file ids are not the same before and after and the file ids which belong to the before part are not available anymore?

2020-11-06 14:28 UTC, gyorb commented on web/server/codechecker_server/api/report_server.py
> +                # has not been fixed before.
But how do we know if it was not fixed ever before? When it gets to the reopen state the fix date will be unset, do we collect somewhere else that the report was in the fixed state?

I just see in the code that the report is in currently in the fixed state and then it is skipped from the detection_status update.
Another question how can a report get into the reopened state? Is that updated somewhere else?

2020-11-06 14:28 UTC, gyorb commented on web/tests/functional/run_tag/test_run_tag.py
> +        run_tags_v0 = [t for t in test_run_tags if t.name == self.tags[0]]
are there any other run tags mixed into the test data, that is why this run tag filtering needed?

2021-01-18 09:31 UTC, csordasmarton commented
This will increment the database size drastically and we don't want to do this. For this reason we handled this problem in a different way. For more information see: #3102.

2021-01-18 09:31 UTC, closed without merging