Less checkers in enable all
Ericsson/codechecker pull request #3013
Opened 2020-11-10 09:11 UTC by gyorb

There is a bugfix and a change in the two commits.
The bugfix is for printing the enabled checkers and the change is to remove more groups from the enable-all configuration.

2020-11-10 09:38 UTC, csordasmarton requested changes

2020-11-10 09:38 UTC, csordasmarton commented on analyzer/codechecker_analyzer/cmd/analyze.py
> +                                    "'llvmlibc-', 'google-', 'zircon-'"
```suggestion
                                    "checker groups 'alpha.', 'debug.', "
                                    "'osx.', 'abseil-', 'android-', "
                                    "'darwin-', 'objc-', 'cppcoreguidelines-', "
                                    "'fuchsia.', 'fuchsia-', 'hicpp-', 'llvm-', "
                                    "'llvmlibc-', 'google-', 'zircon-'"
```
Also fix it in the documentation.

2020-11-10 09:38 UTC, csordasmarton commented on analyzer/codechecker_analyzer/cmd/check.py
> +                                    "'llvmlibc-', 'google-', 'zircon-'"
```suggestion
                                    "checker groups 'alpha.', 'debug.', "
                                    "'osx.', 'abseil-', 'android-', "
                                    "'darwin-', 'objc-', 'cppcoreguidelines-', "
                                    "'fuchsia.', 'fuchsia-', 'hicpp-', 'llvm-', "
                                    "'llvmlibc-', 'google-', 'zircon-'"
```
Also fix it in the documentation.

2020-11-10 13:02 UTC, csordasmarton approved these changes
LGTM!

2020-11-11 08:09 UTC, csordasmarton requested changes
Analyzer related test cases are failed on the travis.

2020-11-11 12:30 UTC, gyorb commented
@bruntib do you have any ideas why the number of  `self.assertEqual(out.count('hicpp-use-nullptr'), 1)` results changed during the tests wasn't these numbers updated when the test environment was updated to clang11?

2020-11-11 15:21 UTC, csordasmarton approved these changes
LGTM!

2020-11-11 15:21 UTC, merged