[test] Introduce Github action for CodeChecker tests
Ericsson/codechecker pull request #3066
Opened 2020-11-30 14:59 UTC by csordasmarton

2020-12-01 12:56 UTC, gyorb requested changes

2020-12-01 12:56 UTC, gyorb commented on .github/workflows/test.yml
> +on: [push, pull_request]
are there triggers for merging to master master branch?

2020-12-01 12:56 UTC, gyorb commented on .github/workflows/test.yml
> +        run: make pylint pycodestyle
are there any javascript linters?

2020-12-01 12:56 UTC, gyorb commented on .github/workflows/test.yml
> +            test_build_logger
where are the tools (plist to html, report_converters, tu_collector ...) tests executed?
Maybe a separate step would be good for them?

2020-12-01 12:56 UTC, gyorb commented on .github/workflows/test.yml
> +          make -C tools/plist_to_html test
Maybe the tools (plist to html, report_converters, tu_collector ...) tests could be executed as a separate job?

2020-12-01 12:56 UTC, gyorb commented on .github/workflows/test.yml
> +    runs-on: ubuntu-latest
Would it be better to select some specific ubuntu version? What is the latest used here? LTS latest (20.04)?
The install_deps.sh assumes that the distribution is ubuntu bionic.

2020-12-02 10:35 UTC, csordasmarton reviewed
My comment for https://github.com/Ericsson/codechecker/pull/3066#discussion_r533382675 comment: we run the JavaScript linters in the GUI related job. For this we have to install node and also run the npm install command which takes too much time. In the gui job it is necessary to install these, so this is the reason why I moved GUI linter test to this job and not to the separate linter job.

2020-12-08 16:18 UTC, gyorb approved these changes

2020-12-08 16:18 UTC, merged