[doc] Documentation for report identification
Ericsson/codechecker pull request #3070
Opened 2020-12-01 16:03 UTC by csordasmarton

> Closes #3031

Describe each hash methods in the documentation.

2020-12-01 20:09 UTC, dkrupp submitted a review, later dismissed
I am missing the references from the user guide to this document. I even did not know that document existed. I think we should refer to this doc from the user_guide.

Please see my comments in the issue also about the missing intro section of the user guide.

"The user guide should have an intro section explaining and summarizing the Features of the CodeChecker command and its subcommands (each one sentences).

The user guide should also have a separate section on Report hashes, because it is a particularly important topic.
Now it is hidden in the help of the check command
"

2020-12-08 16:11 UTC, gyorb requested changes
Please extend with a section with a warning, that the same hash method should be used consistently for a product, mixing them can cause a lot of confusion when the diff or other features are used.

2020-12-16 13:07 UTC, gyorb approved these changes

2020-12-16 13:08 UTC, gyorb commented
@dkrupp do you have any further comments to this change?

2020-12-17 09:52 UTC, merged