[fix][server] review comment parsing with trim path
Ericsson/codechecker pull request #3078
Opened 2020-12-07 18:57 UTC by gyorb

Fixes the source file paths extracted at the server and
used for review status parsing when the trim path
feature was used.
The server depends on the client to send all the source files
containing review status comments. After extraction the
received source files will be parsed for review comments
to update them in the database.
Because the wrong path was used the server did not found
the source file to parse.
The server did not throw any error if a source file was missing
because it is a valid usecase that the client does not send
all the source files because they are already available in the
database at the server side.

New test was added where the review comments were modified
between the two store commands (one with trim path) and then
the successful review comment updates are checked.

2020-12-08 08:30 UTC, csordasmarton requested changes
Just some typos and please check why sqlite related test cases are failed. Otherwise LGTM!

2020-12-08 08:30 UTC, csordasmarton commented on web/server/codechecker_server/api/report_server.py
> +                # The original file path is neded here not the trimmed
```suggestion
                # The original file path is needed here not the trimmed
```

2020-12-08 08:30 UTC, csordasmarton commented on web/server/codechecker_server/api/report_server.py
> +                # filepath.
```suggestion
                # file path.
```

2020-12-08 14:06 UTC, gyorb commented
I'm not sure why the sqlite test failed to cleanup the workspace, I've pushed the changes let's see if it will be successful now/

2020-12-09 08:56 UTC, csordasmarton approved these changes
LGTM!

2020-12-09 08:57 UTC, merged