[gui] Refactoring product overview page
Ericsson/codechecker pull request #3147
Opened 2021-01-15 13:22 UTC by csordasmarton

Add helper tooltips for each widget on the product overview page which
describes the numbers, how these numbers are calculated and what kind of
filter affects these numbers.

2021-01-27 22:46 UTC, bruntib requested changes

2021-01-27 22:46 UTC, bruntib commented on web/server/vue-cli/src/components/Statistics/Overview/ComponentSeverityStatistics/ComponentSeverityStatistics.vue
> +              This table shows a component statistics per severity
```suggestion
              This table shows component statistics per severity
```

2021-01-27 22:46 UTC, bruntib commented on web/server/vue-cli/src/components/Statistics/Overview/ComponentSeverityStatistics/ComponentSeverityStatistics.vue
> +              Each row can be expanded which will show a Checker Statistics
```suggestion
              Each row can be expanded which will show checker statistics
```

2021-01-27 22:46 UTC, bruntib commented on web/server/vue-cli/src/components/Statistics/Overview/ComponentSeverityStatistics/ComponentSeverityStatistics.vue
> +              way.<br><br>
```suggestion
              This pie chart shows the checker severity distribution in the product.<br><br>
```

2021-01-27 22:46 UTC, bruntib commented on web/server/vue-cli/src/components/Statistics/Overview/Overview.vue
> +              <i>x</i> month/days.<br><br>
```suggestion
              <i>x</i> months/days.<br><br>
```

2021-01-27 22:46 UTC, bruntib commented on web/server/vue-cli/src/components/Statistics/Overview/Overview.vue
> +              Reports which marked as <b>False positive</b> or
```suggestion
              Reports marked as <b>False positive</b> or
```

2021-01-27 22:46 UTC, bruntib commented on web/server/vue-cli/src/components/Statistics/Overview/Reports.vue
> +                Reports which marked as <b>False positive</b> or
```suggestion
                Reports marked as <b>False positive</b> or
```

2021-01-27 22:46 UTC, bruntib commented on web/server/vue-cli/src/components/Statistics/Overview/Reports.vue
> +                from a storage.<br><br>
```suggestion
                For now reports marked as <b>False positive</b> or
                <b>Intentional</b> are not considered to be resolved by these numbers.
                A report is marked as resolved only when it disappeared
                from a storage.<br><br>
```

2021-01-27 22:56 UTC, bruntib commented
In my opinion it is very confusing that different diagrams take different filter fields into account. I understand that the fixed "axes" of the diagrams can't be their parameters, but this is exactly what makes them unnecessary.

If we want to keep filter pane on the left, then we should at least visually indicate which fields serve as parameters to the specific diagrams in the future. For example hovering a diagram could fade out and make transparent unused filter fields.

2021-01-28 11:13 UTC, csordasmarton commented
@bruntib Yes, you are right, but now at least the users will see how these numbers are calculated. You can create a separate issue for this problem and we will discuss this problem how we can solve it nicely there.

2021-01-28 11:55 UTC, bruntib approved these changes

2021-01-28 11:55 UTC, merged