Add core.StackAddrEscapeBase checker as HIGH.
Ericsson/codechecker pull request #3369
Opened 2021-06-29 13:28 UTC by AlexisTM

This adds the `core.StackAddrEscapeBase` checker severity as `HIGH`.

The error is currently `Unspecified` and catches dangling references:

> Address of stack memory associated with local variable "Thing" is still referred to by the global variable "thing" upon returning to the caller. This will be a dangling reference.

2021-06-30 12:09 UTC, dkrupp requested changes
core.StackAddrEscapeBase is just a modeling checker for core.StackAddrEscape checker: https://clang.llvm.org/docs/analyzer/checkers.html#core-stackaddressescape-c

In theory it should not emit any warning under this checkername so there should be no need to specify a severity for it. Did you see any direct report from this checker?

2021-06-30 13:53 UTC, AlexisTM commented
I indeed got this error. 

![image](https://user-images.githubusercontent.com/6976744/123972135-e12e8980-d9ba-11eb-8474-13fe3767494f.png)

The code triggering it was like:

something.c
```
static Type* variable; 

void updateVariable() {
    Type data[N];
    variable = &data;
}
```

2021-07-05 08:41 UTC, whisperity commented
@Szelethus Do you have an idea why this might be happening?

2021-07-05 08:56 UTC, Szelethus commented
> @Szelethus Do you have an idea why this might be happening?

This bug should've been fixed a long while ago by https://reviews.llvm.org/D78101. Indeed, with a recent version of clang, this error is correctly emitted under core.StackAddressEscape.

2021-08-17 07:22 UTC, dkrupp commented
> > @Szelethus Do you have an idea why this might be happening?
> 
> This bug should've been fixed a long while ago by https://reviews.llvm.org/D78101. Indeed, with a recent version of clang, this error is correctly emitted under core.StackAddressEscape.

Then we don't need this patch, right? Can it be abandoned?

2021-08-17 07:25 UTC, closed without merging

2021-08-17 07:27 UTC, AlexisTM commented
I closed it as I must have used clang 9 instead of clang 12 causing the issue.