[cli] Local diff workflow support
Ericsson/codechecker pull request #3388
Opened 2021-08-04 12:52 UTC by csordasmarton

- Extend the `CodeChecker parse` command with an extra baseline output type
which can be used to generate a baseline file which will contain
report hashes for legacy reports.
- Extend the `CodeChecker cmd diff` to support baseline files.
- Add test cases.
- Extend the documentation with the recommended usage of this workflow.

2021-08-11 13:39 UTC, bruntib commented on web/client/codechecker_client/cmd_line_client.py
> +    return local_dirs, baseline_files, run_names
The return type hint in line 60 indicates a 2 element tuple.

2021-08-11 13:40 UTC, bruntib commented on web/client/codechecker_client/cmd_line_client.py
> +        elif os.path.isfile(r) and r.endswith(".baseline"):
As I mentioned earlier, I think expecting `.baseline` extension is not necessary. It is enough to check if it is a file here.

2021-08-11 13:42 UTC, bruntib commented on web/client/codechecker_client/cmd_line_client.py
> +            baseline.get_report_hashes(baseline_files))
```suggestion
        local_report_hashes.update(
            baseline.get_report_hashes(baseline_files))
```

2021-08-11 13:43 UTC, bruntib commented on web/client/codechecker_client/cmd_line_client.py
> +            baseline.get_report_hashes(new_baseline_files))
`.update()` could be used here too.

2021-08-12 09:20 UTC, csordasmarton commented on codechecker_common/output/baseline.py
> +    return [h for h in f.read().split('\n') if h]
readlines() will keep white spaces in the lines, so I had to trim the hash-es: `[h.strip() for h in f.readlines() if h]`

2021-08-13 13:09 UTC, bruntib requested changes
I have a few minor comments, but apart from those it looks good to me.

2021-08-17 06:48 UTC, csordasmarton commented on analyzer/codechecker_analyzer/cmd/parse.py
>          if export != 'html':
This is not true, because this branch handles the following export types: 'json', 'codeclimate', 'gerrit'

2021-08-17 12:45 UTC, bruntib approved these changes

2021-08-17 12:45 UTC, merged