[cli][server] Refactoring code for sarif support
Ericsson/codechecker pull request #3462
Opened 2021-10-25 11:02 UTC by csordasmarton

> Closes #3451 and the first part of #1797.

The basic idea behind these changes is that in this patch we created a
general `Report` class which holds information about bugs what are needed
by the CodeChecker CLI and server. We introduced helper functions in this patch
to convert analyzer result files (for now only plist) to Report objects.
All the converters (html, gerrit, codeclimate, json, etc.) and report hash
generation modules will work on these Report objects.

This patch also tried to remove duplication between the different command
line subcommands (parse, diff, store etc.).

2021-11-04 10:43 UTC, bruntib requested changes

2021-11-04 10:43 UTC, bruntib commented on tools/report-converter/codechecker_report_converter/analyzers/clang_tidy/parser.py
> +            print("ADD NOTE 1")
```suggestion
```

2021-11-05 13:53 UTC, bruntib approved these changes

2021-11-05 13:58 UTC, merged

2021-11-23 14:39 UTC, csordasmarton commented
The json output of the `CodeChecker parse` command was not stable enough and the structure was very similar to the plist structure. Our plan is to support reading/parsing/storing of multiple analyzer output types not only plist but for example sarif format as well (http://docs.oasis-open.org/sarif/sarif/v2.0/csprd01/sarif-v2.0-csprd01.html).

Yes, it's our mistake that we forgot to mention it in the release notes. So sorry for that :/