[test][cfg] Use clang-13 in the CI, uplift tests accordingly
Ericsson/codechecker pull request #3475
Opened 2021-11-02 15:32 UTC by steakhal

The `-Wunused-but-set-variable` and `-Wunused-but-set-parameter` warnings were introduced by https://reviews.llvm.org/D100581, so had to suppress these warnings in the test file to make them forward compatible.

Let's see if the build bots are happy.

2021-11-02 15:39 UTC, csordasmarton requested changes
Can you please change the version number in this file too:
https://github.com/Ericsson/codechecker/blob/4be1ecad9249470171a623feeacf17da83858fce/scripts/test/check_clang.py#L20-L21

2021-11-02 15:41 UTC, steakhal commented
> Can you please change the version number in this file too:
> 
> https://github.com/Ericsson/codechecker/blob/4be1ecad9249470171a623feeacf17da83858fce/scripts/test/check_clang.py#L20-L21

The tests seem to run even on clang-11.

2021-11-02 16:19 UTC, steakhal commented
From the log, it's not clear to me what is failing. Any guidance?

2021-11-03 13:38 UTC, csordasmarton approved these changes
LGTM!

2021-11-03 13:38 UTC, merged