WIP - Prefer ldlogger over intercept-build
Ericsson/codechecker pull request #3605
Opened 2022-02-24 09:42 UTC by steakhal

1st check if LDlogger is available and use that.
2nd check if intercept-build is available and use that.
3rd Otherwise report an error.

2022-02-24 10:12 UTC, csordasmarton requested changes

2022-02-24 10:12 UTC, csordasmarton commented on analyzer/tests/functional/analyze_and_parse/__init__.py
> +
This is not needed, the CC_LIB_DIR is set by the top level script file:
```suggestion
```

2022-02-24 10:12 UTC, csordasmarton commented on analyzer/codechecker_analyzer/buildlog/host_check.py
> +            data_files_dir_path, 'ld_logger', 'lib', '*', 'ldlogger.so')
```suggestion
    logger_lib_dir_path = os.path.join(
        data_files_dir_path, 'ld_logger', 'lib', '*', 'ldlogger.so')
```

2022-02-24 10:12 UTC, csordasmarton commented on analyzer/codechecker_analyzer/buildlog/host_check.py
> +def check_ldlogger(env):
```suggestion
def check_ldlogger(env) -> bool:
```

2022-02-24 10:12 UTC, csordasmarton commented on analyzer/codechecker_analyzer/buildlog/build_manager.py
> +    if host_check.check_ldlogger(original_env):
The original_env doesn't contain environment variable which are set by the top level script and using this function. For this reason use the current environment:
```suggestion
    if host_check.check_ldlogger(os.environ):
```

2022-02-24 10:12 UTC, csordasmarton commented on analyzer/codechecker_analyzer/buildlog/build_manager.py
> +    # Otherwise try to fall back to intercept-build.
Now the logger detection looks like this:
```py
if ld_logger:
  if LINUX:
    ...
  elif WINDOWS:
    ...
  else:
    ...
elif intercept_build:
  ...
else:
  ...
```

Wouldn't it be better to use the following check:
```py
if ld_logger:
  ...
elif intercept_build:
  ...
else: # No intercept build or ld-logger
  if LINUX:
    ...  # Install ld-logger or intercept-build
  elif WINDOWS:
    ...  # Original log message.
  else:
    ...  # Install intercept-build
```

2022-02-24 12:05 UTC, steakhal commented
I don't want to make further changes, since the CI is already breaks.

2022-02-24 15:23 UTC, csordasmarton commented on analyzer/codechecker_analyzer/buildlog/host_check.py
> +        lib_dir_path, 'codechecker_analyzer', 'ld_logger', 'lib', '*',
```suggestion
        lib_dir_path, 'codechecker_analyzer', 'ld_logger', 'lib', '**',
```

2022-02-24 15:23 UTC, csordasmarton commented on analyzer/codechecker_analyzer/buildlog/host_check.py
> +    asd = glob.glob(alternative_logger_lib_dir_path)
```suggestion
    asd = glob.glob(alternative_logger_lib_dir_path, recursive=True)
```

2022-02-24 15:23 UTC, csordasmarton commented on analyzer/codechecker_analyzer/buildlog/host_check.py
> +        data_files_dir_path, 'ld_logger', 'lib', '*', 'ldlogger.so')
```suggestion
        data_files_dir_path, 'ld_logger', 'lib', '**', 'ldlogger.so')
```

2022-02-24 15:23 UTC, csordasmarton commented on analyzer/codechecker_analyzer/buildlog/host_check.py
> +    asd = glob.glob(logger_lib_dir_path)
```suggestion
    asd = glob.glob(logger_lib_dir_path, recursive=True)
```

2022-02-25 07:49 UTC, csordasmarton approved these changes
LGTM!

2022-02-25 07:49 UTC, merged