[config][CLI] Merge, and don't override when multiple --analyzer-configs are specified
Ericsson/codechecker pull request #3655
Opened 2022-04-21 13:39 UTC by Szelethus

Previous to this patch, multiple analyzer configs could be specified
like this:

CodeChecker analyze ./compile_commands.json -o ./reports -c --verbose debug \
  --analyzers clang-tidy \
  --analyzer-config clang-tidy:HeaderFilterRegex=".*" clang-tidy:AnalyzeTemporaryDtors="true"

However, if you specifiy --analyzer-config more than once, the only the
last one counts, like many other flags.

The problem is that --analyzer-config may be specified from both the CLI
and a CodeChecker config file, and even in this case, only one of these
would count.

Also, the -analyzer-config flag from the Clang Static Analyzer works
differently, as multiple -analyzer-configs in the invocation and
appended, not overwritten. Coming from that space, that philosophy feels
more intuitive to me, and I think other users may be out these who might
be suprised by this behaviour.

This patch merges --analyzer-config (we append the list of configs)
values instead of overwriting them.

2022-04-25 21:05 UTC, bruntib requested changes
Just two minor comments, otherwise it looks good.

2022-04-25 21:05 UTC, bruntib commented on analyzer/codechecker_analyzer/arg.py
> +               " but should be if nargs is not None!"
Might be useful to know that strings can be assembled simpler:
```suggestion
               f"--analyzer-config value  ({value}) is not a list," \
               " but should be if nargs is not None!"
```

2022-04-27 12:30 UTC, Szelethus commented
It appears that currently --config overrides CLI arguments. I need to dig tothe bottom of that before merging.

2022-04-28 07:46 UTC, bruntib commented on analyzer/tests/functional/config/test_config.py
> +        very same config, CLI arguments override the config file.
I think we need to rephrase it. A command line option doesn't override the ones In config file, but appends it to a later position in the analyzer command.

2022-04-28 13:16 UTC, Szelethus commented
When this lands, CLI arguments will be present twice in `analyzer_config` after all arguments are parsed. This is becaused the CLU arguments are parsed to check the value of `--config`, that file is parsed and prepended to the CLI argument list, and that whole thing is parsed again.

This isn't an immediate concern (the latest argument will come to effect, which will be the CLI one), but isn't too pretty either. We should likely not parse all command line arguments twice anyways.

2022-04-29 09:57 UTC, bruntib commented
Based on a discussion in our team, these to things should also be included in this pull request:
- Eliminate duplication when using both config file and command line flag: #3665
- Duplicate analyzer/checker config options should also be eliminated if a specific analyzer/checker occurs both in config file and command line.

2022-05-11 10:02 UTC, bruntib commented on analyzer/codechecker_analyzer/arg.py
> +               " but should be if nargs is not None!"
```suggestion
               f"--analyzer-config or --checker-config value ({value}) is not a list," \
               " but should be if nargs is not None!"
```

2022-05-11 10:03 UTC, bruntib commented on analyzer/codechecker_analyzer/arg.py
> +    Action to store --analyzer-config values. These may come from many sources,
```suggestion
    Action to store --analyzer-config and --checker-config values. These may come from many sources,
```

2022-05-11 11:53 UTC, bruntib approved these changes

2022-05-11 11:54 UTC, merged