Import the suppressions per report
Ericsson/codechecker pull request #3693
Opened 2022-06-24 12:12 UTC by dkrupp

CodeChecker cmd suppress run_name -i <import_file>
will only import suppressions for the run indicated by run_name,
and not all reports.

Suppressions are imported as single report suppressions
instead of suppression rules.

This is the behaviour the user expects when run name is given
as a parameter to the command.

This patch also fixes the changeReviewStatus(report_id, status, message)
API function to change the review status of a single report only
instead of all reports with the same hash.

2022-06-27 12:45 UTC, bruntib requested changes

2022-06-27 12:45 UTC, bruntib commented on docs/web/user_guide.md
> +retrieving, should be done.
```suggestion
Several sub-commands, such as `store` and `cmd` need a connection specification
that identifies a CodeChecker server and a *Product* (read more [about products](products.md).
Actions like report storage or result retrieving are performed towards this server and product.
```

2022-06-27 12:45 UTC, bruntib commented on docs/web/user_guide.md
> +`[http[s]://]host:port/ProductEndpoint`. This URL looks like a standar Web
```suggestion
`[http[s]://]host:port/ProductEndpoint`. This URL looks like a standard Web
```

2022-06-29 10:00 UTC, dkrupp commented on web/server/codechecker_server/api/report_server.py
> +                    if report.detection_status in [
fixed

2022-06-29 10:09 UTC, dkrupp commented on docs/web/user_guide.md
> -    CodeChecker check -b "cd ~/myproject && make"
I don't think we need this check related part in the web user guide.

2022-06-29 10:40 UTC, dkrupp commented
I fixed all your comments. Ready to be merged.

2022-07-05 08:20 UTC, dkrupp commented on docs/web/user_guide.md
> +#### `PRODUCT_URL` format
fixed

2022-07-05 12:06 UTC, bruntib approved these changes

2022-07-06 11:22 UTC, merged