Refactoring the analyzer user guide
Ericsson/codechecker pull request #3694
Opened 2022-06-24 14:32 UTC by dkrupp

2022-08-17 09:49 UTC, bruntib requested changes
Some typos could also be fixed. Please grep them, because some of these are occurring in the source code too (i.e. help pages).

performend
withhout
Execuing
analyse
analysers
expaneded
analysing
interations

2022-08-17 09:49 UTC, bruntib commented on docs/analyzer/user_guide.md
> +##### _Skip_ file
```suggestion
#### _Skip_ file
```

2022-08-17 09:49 UTC, bruntib commented on docs/analyzer/user_guide.md
> +####### Absolute path examples
```suggestion
##### Absolute path examples
```

2022-08-17 09:49 UTC, bruntib commented on docs/analyzer/user_guide.md
> +####### Relative or partial path examples
```suggestion
##### Relative or partial path examples
```

2022-08-17 09:49 UTC, bruntib commented on docs/analyzer/user_guide.md
> +##### CodeChecker analyzer configuration
```suggestion
#### CodeChecker analyzer configuration
```

2022-08-17 09:49 UTC, bruntib commented on docs/analyzer/user_guide.md
> +###### Analyzer and checker config options
```suggestion
##### Analyzer and checker config options
```

2022-08-17 09:49 UTC, bruntib commented on docs/analyzer/user_guide.md
> +###### Configuration of analyzer tools
```suggestion
##### Configuration of analyzer tools
```

2022-08-17 09:49 UTC, bruntib commented on docs/analyzer/user_guide.md
> +###### Configuration of checkers
```suggestion
##### Configuration of checkers
```

2022-08-17 09:49 UTC, bruntib commented on docs/analyzer/user_guide.md
> +###### Forwarding compiler options
```suggestion
##### Forwarding compiler options
```

2022-08-17 09:49 UTC, bruntib commented on docs/analyzer/user_guide.md
> +###### _Clang Static Analyzer_
```suggestion
##### _Clang Static Analyzer_
```

2022-08-17 09:49 UTC, bruntib commented on docs/analyzer/user_guide.md
> +#########_Clang-Tidy_
```suggestion
##### _Clang-Tidy_
```

2022-08-17 09:49 UTC, bruntib commented on docs/analyzer/user_guide.md
> +###### Compiler-specific include path and define detection (cross compilation)
```suggestion
##### Compiler-specific include path and define detection (cross compilation)
```

2022-08-17 09:49 UTC, bruntib commented on docs/analyzer/user_guide.md
> +##### Toggling checkers
```suggestion
#### Toggling checkers
```

2022-08-17 09:49 UTC, bruntib commented on docs/analyzer/user_guide.md
> +##### Toggling compiler warnings
```suggestion
#### Toggling compiler warnings
```

2022-08-17 09:49 UTC, bruntib commented on docs/analyzer/user_guide.md
> +##### Checker profiles
```suggestion
#### Checker profiles
```

2022-08-17 09:49 UTC, bruntib commented on docs/analyzer/user_guide.md
> +####### `--enable-all`
```suggestion
##### `--enable-all`
```

2022-08-17 09:49 UTC, bruntib commented on docs/analyzer/user_guide.md
> +##### Cross Translation Unit (CTU) analysis mode
```suggestion
#### Cross Translation Unit (CTU) analysis mode
```

2022-08-17 09:49 UTC, bruntib commented on docs/analyzer/user_guide.md
> +##### Taint analysis configuration
```suggestion
#### Taint analysis configuration
```

2022-08-17 09:49 UTC, bruntib commented on docs/analyzer/user_guide.md
> +##### Statistical analysis mode
```suggestion
#### Statistical analysis mode
```

2022-08-17 09:49 UTC, bruntib commented on docs/analyzer/user_guide.md
> +* [Applying code fixes](#fixes)
```suggestion
* [Applying code fixes](#fixit)
```

2022-08-19 11:31 UTC, dkrupp commented
Thanks for the review. I fixed everything.

2022-08-19 11:42 UTC, bruntib approved these changes

2022-08-19 13:01 UTC, Szelethus reviewed
I wonder how much the "JSON Compilation Commands" file is common knowledge. Maybe it could be a hyperlink to this: https://clang.llvm.org/docs/JSONCompilationDatabase.html. Also, while CodeChecker log is mentioned, there is no "More on compilation databases and CodeChecker log in section x.x". A reference to that section might be nice. It says to "see the individual help for log, analyze and parse (below in this User guide) for information about the arguments which are not documented here", but explicitly stating that all log basically does is that json database might be nice.

I was missing this under the "log" section as well. It states:
> The first step in performing an analysis on your project is to record information about the files in your project for the analyzers. This is done by recording a build of your project, which is done by the command CodeChecker log.

Why doesn't it state explicitly that what is being created is this once-mentioned JSON compilation database?

This is all notpicking, I couldn't get much further due to other issues I needed to attend to. Make a judgement call whether you want to address them.

2022-08-19 13:32 UTC, dkrupp commented
> I wonder how much the "JSON Compilation Commands" file is common knowledge. Maybe it could be a hyperlink to this: https://clang.llvm.org/docs/JSONCompilationDatabase.html. Also, while CodeChecker log is mentioned, there is no "More on compilation databases and CodeChecker log in section x.x". A reference to that section might be nice. It says to "see the individual help for log, analyze and parse (below in this User guide) for information about the arguments which are not documented here", but explicitly stating that all log basically does is that json database might be nice.
> 
> I was missing this under the "log" section as well. It states:
> 
> > The first step in performing an analysis on your project is to record information about the files in your project for the analyzers. This is done by recording a build of your project, which is done by the command CodeChecker log.
> 
> Why doesn't it state explicitly that what is being created is this once-mentioned JSON compilation database?
> 
> This is all notpicking, I couldn't get much further due to other issues I needed to attend to. Make a judgement call whether you want to address them.

Thanks for the review. I extended the descriptions.

2022-08-19 13:59 UTC, merged