[bugfix] Fix system include path order
Ericsson/codechecker pull request #3735
Opened 2022-09-02 15:09 UTC by bruntib

The implicit include paths should be added after the user-defined flags
and include paths even in the pre-ctu phase, otherwise the build commands
will not be equivalent with the original ones.

2022-09-08 10:39 UTC, vodorok approved these changes
Looks good to me, @martong could you please also take a look?

2022-09-08 12:28 UTC, Szelethus requested changes
Could you expand on why is this needed? I find the summary lacking a bit.

2022-09-08 12:28 UTC, Szelethus commented on analyzer/tests/functional/ctu/test_ctu.py
> +        user-defined flags and include paths in the pre-ctu phase.
You describe the "what", but not the "why". Why is this important?

2022-09-13 15:07 UTC, Szelethus requested changes
Please update the commit message with the bit you wrote in the test file. You used the phrase "The two build commands will not be equivalent", but I don't think that captures what the problem really is. The problem is that we will analyze the files with the wrong set of build commands, because we messed up processing the build command json. When you mention equivalence, I immediately think of storing elements in a set, trying to query a specific build from a database, or something algebraic like that.

2022-09-14 09:27 UTC, Szelethus approved these changes
Please add that FYI comment to `analyzer/codechecker_analyzer/analyzers/clangsa/ctu_triple_arch.py` as well. Otherwise LGTM, merge at your leisure.

2022-09-14 10:43 UTC, merged