[fix] Apply all fixits
Ericsson/codechecker pull request #3754
Opened 2022-10-03 13:09 UTC by bruntib

Clang tidy may provide automatically applicable fixits. These can be applied by clang-apply-replacements tool. This tool gets a directory as input which contains .yaml files describing the replacements. If any of these .yaml files can't apply for some reason, then the rest is skipped.

This clang tool is added a flag named --ignore-insert-conflict which ignores the error event and continues the application of further .yaml files. If CodeChecker recognizes the existence of this flag then it will be used, otherwise CodeChecker creates a temporary directory with a single .yaml file and applies them one by one.

2022-10-27 07:59 UTC, Szelethus requested changes
Well... do you have tests for this? :)

2022-11-09 15:29 UTC, Szelethus approved these changes
LGTM

2022-11-09 15:29 UTC, Szelethus commented on analyzer/codechecker_analyzer/cmd/fixit.py
> +    if reports is not None and 'version' in reports:
```suggestion
    if reports and 'version' in reports:
```

2022-11-09 15:29 UTC, Szelethus commented on analyzer/tests/functional/fixit/test_fixit.py
> +        # Toudh file so "CodeChecker fixit" doesn't apply on the first file.
```suggestion
        # Touch file so "CodeChecker fixit" doesn't apply on the first file.
```

2022-11-09 15:38 UTC, vodorok approved these changes
LGTM

2022-11-09 15:45 UTC, merged