Typos a/an
Ericsson/codechecker pull request #3776
Opened 2022-10-22 09:55 UTC by dilyanpalauzov

Replace SSL → TLS.

2022-10-22 10:00 UTC, dilyanpalauzov commented on analyzer/tools/build-logger/src/ldlogger-logger.c
> +  /* fclose() also closes the file descriptor, so we only call fflush()
> fclose() also closes the file descriptor, so we only call fflush() here

Here it might be meant, that fclose() also FLUSHES the file descriptor.

2022-10-22 10:02 UTC, dilyanpalauzov commented on analyzer/tools/build-logger/src/ldlogger-logger.c
> +  /* fclose() also closes the file descriptor, so we only call fflush()
No, this is not meant here.

2022-10-24 08:47 UTC, whisperity commented on docs/web/user_guide.md
> +#### Enfore secure socket (TLS)
I'd not **replace** SSL with TLS but if we want to mention TLS then let's mention both. The terminology common to many people involved in running servers and web connection is still "SSL", and not saying "TLS", no matter how wrong this is. If people are just searching the documentation how to use SSL, they will no longer have findings related to this (to some very important) feature.

2022-10-24 09:23 UTC, dilyanpalauzov commented
I have replaced SSL with TLS/SSL.

There is no such thing like SSL certificate or TLS certificate, but PEM or DER certificate.  The documentation says now TLS certificate.

2022-10-24 12:44 UTC, whisperity commented
> There is no such thing like SSL certificate or TLS certificate

While this might be true if you are talking on a highly technical level, it's unfortunately not true for people who are administrators or users of web technologies. In fact, [DigiCert](http://www.digicert.com/what-is-an-ssl-certificate), [Cloudflare](http://www.cloudflare.com/en-gb/learning/ssl/what-is-an-ssl-certificate/), [Go Daddy](http://www.godaddy.com/en-uk/web-security/ssl-certificate) and [VeriSign](http://www.verisign.com/en_US/website-presence/online/ssl-certificates/index.xhtml) all call the entity we are talking about `SSL Certificate`, and in fact when you go as much down (in terms of search engine results, after having bypassed the ads) to reach [*Let's Encrypt!*](https://letsencrypt.org/), they are the ones who say `TLS Certificate` on their site.

2022-10-24 13:36 UTC, bruntib approved these changes
@whisperity feel free to merge this PR if you think this SSL/TLS description is correct. Thanks for the patch and the review!

2022-10-27 07:31 UTC, dilyanpalauzov commented
> Have you found any more accidental typos?

No

2022-10-29 11:19 UTC, whisperity commented on docs/web/user_guide.md
>                          (default: /home/<username>/.codechecker)
These texts should be in synch with the contents of the Python script that generates the help when the user says `--help`. Please add the same change to

https://github.com/Ericsson/codechecker/blob/01a042ce6442f66d007fbca750951f6f904d350c/web/server/codechecker_server/cmd/server.py#L89-L97

Then we can merge! :smile:

2022-10-29 11:19 UTC, whisperity requested changes
&nbsp;

2022-10-31 14:29 UTC, whisperity approved these changes

2022-10-31 14:30 UTC, merged

2022-10-31 14:30 UTC, whisperity commented
@Szelethus Perhaps this would be worthwhile to cherry-pick to **6.21**. No need for a release notes entry.