[bugfix] Required format for --checker-config
Ericsson/codechecker pull request #3817
Opened 2023-01-16 10:29 UTC by bruntib

--checker-config flag needs to have the following format: <analyzer>:<checker>:<option>=<value>

If the format is not met then CodeChecker should print an error message.

2023-01-16 10:38 UTC, bruntib commented
Please don't review it yet. I'd rather like to give a whole different implementation for this issue.

2023-01-20 15:40 UTC, bruntib commented
The alternative implementation is done, it can be reviewed.

2023-01-24 12:40 UTC, Szelethus approved these changes
LGTM, I guess! I like that the code in most places got a lot simpler.

2023-02-03 12:56 UTC, Szelethus requested changes
My usual gripe -- please, cope the commit message to the description.

2023-02-03 12:56 UTC, Szelethus commented on analyzer/codechecker_analyzer/arg.py
> +            f"Checker option in wrong format: {arg}")
...should be 
```suggestion
            f"Checker option in wrong format: {arg}, should be <analyzer>:<checker>:<option>=<value>")
```

2023-02-06 17:09 UTC, vodorok requested changes
Please see my remarkts

2023-02-06 17:09 UTC, vodorok commented on analyzer/tests/functional/cmdline/test_cmdline.py
> +        self.assertIn("Checker option in wrong format", err)
Can you make a negative testcase for testing a mistyped analyzer option too?

2023-02-06 17:09 UTC, vodorok commented on docs/analyzer/user_guide.md
> +                        analyzer configuration file in case of Clang Tidy
Nitpick, but for my ears this rings better: ...To use an analyzer configuration...

2023-02-06 17:09 UTC, vodorok commented on docs/analyzer/user_guide.md
> +                        a -config flag then those options extend these. To use
Nitpick, but for my ears this rings better: ...To use an analyzer configuration...

2023-02-24 09:32 UTC, bruntib commented on analyzer/codechecker_analyzer/arg.py
> +            "<analyzer>:<checker>:<option>=<value>")
Could you please give an example?

2023-03-24 13:25 UTC, vodorok approved these changes
LGTM

2023-03-24 13:32 UTC, Szelethus approved these changes
LGTM

2023-03-24 13:33 UTC, merged