[cmd] Remove --tidy-config flag
Ericsson/codechecker pull request #3822
Opened 2023-01-19 17:17 UTC by bruntib

CodeChecker analyze --tidy-config is a rarely used and redundant flag. ClangTidy options can be given through .clang-tidy file, --analyzer-config, --checker-config and --tidyargs flags.

2023-01-20 09:43 UTC, Szelethus commented
I agree, though maybe it'd be more user friendly if we would depracate this flag first.

2023-01-20 14:57 UTC, Szelethus requested changes
In my view, this is the worst way to depracate a feature. You are removing the functionality behind the flag, but not the flag itself, leaving those that don't read warning messages (imagine multi-thousand line CI jobs, or integrated environments like vscode) to think that their configuration works, but it doesn't.

Mind that tidy configs are usually low-impact: its easy to not notice that the feature is off.

You should either
* Remove the flag altogether;
* Keep the functionality, but warn that its been deprecated and will be removed in an upcoming release.

2023-01-25 08:52 UTC, bruntib commented
Alright, I restored the flag's functionality. It will be removed in the next release.

2023-01-31 12:44 UTC, Szelethus reviewed
Please create a warning for when the flag is used, warning about the removal in the next release. Otherwise LGTM.

2023-01-31 12:44 UTC, Szelethus commented on analyzer/codechecker_analyzer/analyzers/clangtidy/analyzer.py
> +        If 'Checks' option is specified through the '--analyzer-config'
```suggestion
        If 'Checks' option is specified through '--analyzer-config'
```

2023-02-03 12:17 UTC, Szelethus approved these changes

2023-02-03 12:17 UTC, merged