Recognize symlinks in compilation database and eliminate duplication
Ericsson/codechecker pull request #3850
Opened 2023-02-24 23:49 UTC by Ducnguyen147

Previously, the compilation database JSON file could potentially include duplicate entries for files that were symlinked. This caused issues when building the project as it would result in multiple compilations of the same file. To solve this problem, script was modified to recognize symlinks and eliminate any duplicate entries in the compilation database. This ensures that each file is only compiled once, reducing build times and avoiding errors.

2023-02-27 20:18 UTC, vodorok requested changes
Hi Ducnguyen147, 
Thank you for your contribution. 
Please see my remarks.
Please modify the help texts in the `cmd/analyze.py` and `cmd/check.py` as this new option is not yet reflected in the help messages of the respective parameters. There is a section in the `docs/analyzer/user_guide.md` too.
Also, I would like to see some tests.

@bruntib  please challenge the comments in this review.

2023-02-27 20:32 UTC, vodorok commented
Sorry, my initial review comments were lost, that's why the edits. Keep up the good work! :rocket:

2023-02-27 20:57 UTC, Ducnguyen147 commented
Sorry I just click on the wrong re-request button. Thank you for your suggestions @vodorok 👏, I’m on your comments

2023-02-28 09:39 UTC, vodorok commented
No worries!

2023-02-28 10:22 UTC, bruntib requested changes
The direction is good, thanks for the patch!

2023-02-28 10:22 UTC, bruntib commented on analyzer/codechecker_analyzer/buildlog/log_parser.py
> +                if (not is_symlink(source_file)) or\
The example is good, but we'd like to recognize symlink directories too. So this example could be extended by `dirE` which is a symlink to `dirA`.

2023-02-28 10:22 UTC, bruntib commented on analyzer/codechecker_analyzer/buildlog/log_parser.py
> +    parent_dir = os.path.abspath(filepath)
As @vodorok mentioned in another comment, the "directory" and "file" components always need to be handled together. `os.path.abspath()` returns an absolute path of the given file, but the current working directory will be used as prefix.

2023-03-07 23:09 UTC, Ducnguyen147 commented
Dear @vodorok and @bruntib , the log_parser.py file has been edited. You can review it!

2023-03-07 23:12 UTC, Ducnguyen147 commented
I'm working on the help texts! Thank you!

2023-04-12 16:41 UTC, bruntib approved these changes

2023-04-13 11:38 UTC, merged