[analyzer] Fix crash when an assembler command is analyzed
Ericsson/codechecker pull request #3914
Opened 2023-05-18 13:42 UTC by bruntib

If an assember command is analyzed then the recognized language remains None which can't be provided after -x flag in a subprocess.Popen call. So -x is added to the command if the recognized language is not None.

Fixes #3670

2023-05-18 20:09 UTC, nolange commented
I am not sure if GCC would give you useful output without specifying language.
Wouldn't it be better to just skip files that aren't supported?

2023-05-18 21:11 UTC, nolange commented
In this case it is nasm that is called, not GCC, and it is called without any file.

I believe you are trying to find out default include paths here, how does that work - all unsupported Extension map map to none, first one gets called even if it is not GCC and you can't even parse the output?

As for what I would be doing, for default includes stick to the languages (compilers?) you know, skip the rest.
Maybe extend the list of known languages that are supported with -x.

2023-05-19 04:08 UTC, whisperity commented
@bruntib Could you please check if this also fixes #3730? The two issues sound similar following a superficial read.

2023-05-19 12:10 UTC, bruntib commented
@nolange I created another implementation which doesn't call the implicit include path collector if the language is not recognized. The build action itself is skipped in this case even today, so only this crash should be eliminated.
https://github.com/Ericsson/codechecker/blob/a07a74a6c74ab78c134fc94737edb264eeae5f69/analyzer/codechecker_analyzer/buildlog/log_parser.py#L1296-L1297

@whisperity Yes, it fixes that ticket too. I added it to the commit message.

2023-05-25 13:37 UTC, vodorok requested changes
One small question

2023-05-25 13:37 UTC, vodorok commented on analyzer/tests/unit/test_option_parser.py
> +        print(res)
Is this print necessary?

2023-05-25 13:47 UTC, bruntib commented
I just copy-pasted it from the other test cases. I don't know.

2023-05-25 14:14 UTC, vodorok approved these changes
LGTM

2023-05-25 14:14 UTC, merged