clang-tidy report converter now supports clang17 fixit format
Ericsson/codechecker pull request #4052
Opened 2023-10-20 13:39 UTC by dkrupp

clang-tidy version 17 introduced a new fixit diagnostic formatting. The report converter is now prepared to parse this new format. It also still supports the old format.

2023-10-20 13:50 UTC, dkrupp commented
Fixes #4047

2023-10-24 10:29 UTC, whisperity requested changes

2023-10-24 10:29 UTC, whisperity commented on tools/report-converter/codechecker_report_converter/analyzers/clang_tidy/parser.py
> +        # "       fixit-text"
```suggestion
        # Matches pre Clang 17 fix-its:
        # "       fixit-text"
```

2023-10-24 10:29 UTC, whisperity commented on tools/report-converter/codechecker_report_converter/analyzers/clang_tidy/parser.py
> +        # "   28 |     fixit-text"
```suggestion
        # Matches post Clang 17 fix-its:
        # "   28 |     fixit-text"
```

2023-10-24 10:29 UTC, whisperity commented on tools/report-converter/codechecker_report_converter/analyzers/clang_tidy/parser.py
> +            message_text = match.group("message")
```suggestion
            match = self.fixit_new_re.match(line)
            if not match:
                match = self.fixit_old_re.match(line)
                message_text = match.group("message")
                # Until Clang 16, the FixIt line starts with whitespace.
                col = line.find(message_text) + 1
            else:
                message_text = match.group("message")
                # In newer versions, we have whitespace then, optionally
                # a line number, and then a | character.
                col = line.find(message_text) - line.find("|") - 1
```

2023-10-24 10:32 UTC, whisperity commented
With the suggested changes, this looks fine for 6.23, but for 6.24 we should consider dropping the conversion from "random meaningless stdout text" to plist in favour of "well-formatted message and fix YAML" to plist. For a very long time now, Clang-Tidy was capable of dumping the structure of the created diagnostics (all the notes, warnings, and fixits, see https://github.com/llvm/llvm-project/blob/llvmorg-17.0.0/clang-tools-extra/test/clang-tidy/infrastructure/export-diagnostics.cpp!) in YAML.

2023-10-27 08:35 UTC, whisperity approved these changes
LGTM.

2023-10-27 08:39 UTC, merged