[cfg] Fix readthedocs not properly building
Ericsson/codechecker pull request #4072
Opened 2023-11-06 15:45 UTC by vodorok

2023-11-06 16:08 UTC, vodorok commented
A dependency update of mkdocs was also needed to successfully build the docs.
You view it  here: https://vodorokcodechecker.readthedocs.io/en/latest/

2023-11-06 17:00 UTC, bruntib requested changes

2023-11-06 17:00 UTC, bruntib commented on requirements_py/docs/requirements.txt
> +mkdocs==1.5.3
This lib is used in other files too. Please, upgrade those as well:
./requirements_py/docs/requirements.txt
./analyzer/requirements_py/dev/requirements.txt
./web/requirements_py/dev/requirements.txt

2023-11-07 10:06 UTC, bruntib approved these changes

2023-11-07 10:06 UTC, merged