[analyze] Removing long enabled checker list at info log level
Ericsson/codechecker pull request #4103
Opened 2023-11-27 18:41 UTC by dkrupp

At every analysis at the defult log level there was a wall of text checker list. It is enough to print this list at the verbose log level and redirect the user to the metadat.json file at default log level.

2023-12-07 12:06 UTC, whisperity commented on analyzer/codechecker_analyzer/analyzer.py
> +             os.path.join(args.output_path, "metadata.json"))
```suggestion
    LOG.info("Enabled checker list can be found in %s",
             os.path.join(args.output_path, "metadata.json"))
```

2024-02-19 08:51 UTC, Szelethus commented
I totally support this patch -- the default output is still let a little loose on verbosity. With that said, metadata.json isn't very human readable without formatting, so we should consider prettifying it.

2024-03-27 10:47 UTC, whisperity commented
@Szelethus The `metadata.json` is not meant to be human-readable. It is a completely internal format and transitional medium, we should not suggest, direct, or expect users to do anything with it.

`CodeChecker parse` `--details`(?), however, could emit this list. Maybe as a proper list, not a huge concatenated string, which was also barely readable due to the difference in lengths. `clang-tidy --list-checks --checks='*'` emits a formatted list, one element per line.

2024-03-27 10:47 UTC, whisperity requested changes
&nbsp;

2024-03-27 10:48 UTC, whisperity requested changes
(Reasoning above.)

2024-03-27 10:48 UTC, whisperity commented on analyzer/codechecker_analyzer/analyzer.py
> +             os.path.join(args.output_path, "metadata.json"))
```suggestion
```

2024-03-27 10:48 UTC, whisperity commented on analyzer/codechecker_analyzer/analyzer.py
>          k + ': ' + ', '.join(v) for k, v in enabled_checkers.items()))
Good, but maybe could be formatted into one line for each checker.

2024-05-29 08:52 UTC, whisperity approved these changes

2024-05-29 08:54 UTC, merged