[analyzer][clang] Remove external plugin support
Ericsson/codechecker pull request #4112
Opened 2023-12-05 10:28 UTC by gamesh411

Shipping plugins as external dynamic libraries for Clang Static Analyzer is generally frowned upon, and not supported. This patch removes the existing support for using external ClangSA analyzer plugins.

2024-03-21 13:40 UTC, bruntib commented
I agree that the plugins could be provided by `--saargs`, so I approve this patch. But what do you mean by "not supported"? Clang 17 still has a `-load` flag for loading plugins.

2024-03-21 15:07 UTC, whisperity commented
> But what do you mean by "not supported"? Clang 17 still has a `-load` flag for loading plugins.

There is also [`-fplugin=`](https://clang.llvm.org/docs/ClangPlugins.html), which provides a higher-level interface.

It is not supported in the sense that you will get no help ("support") in using that feature, including help about crappy results, crashes, complete and utter corruption of your filesystem, exploits, etc. The official stance of **CSA** (but not necessarily Clang as a whole!), is that if you use plugins and anything goes wrong, you're &mdash; for the lack of a better phrase &mdash; [**SOL**](https://www.urbandictionary.com/define.php?term=SOL). (It's like reporting a kernel panic of a [tainted kernel](https://docs.kernel.org/admin-guide/tainted-kernels.html) (a kernel that had proprietary `ko`s (drivers) loaded into it), the number one reply you'll get on the mailing list is that your crash report is disregarded.) It is your own and absolute responsibility to deal with every consequence that stems from having a plugin.

And because it is unsupported, there are no guarantees that whatever code you create and potentially distribute as a plugin will work with any arbitrary Clang version. They don't care about API or ABI compatibility.

2024-03-25 13:16 UTC, whisperity commented
@bruntib will have comments.

2024-03-26 13:33 UTC, whisperity requested changes
@bruntib will have comments.

2024-03-27 10:23 UTC, whisperity requested changes
@gamesh411 I'll summarise what I discussed with @bruntib prior because it looks like they hadn't gotten around to publishing their comments so far.

2026-03-20 01:41 UTC, closed without merging