[fix] Creating new temporary directory for zip files
Ericsson/codechecker pull request #4237
Opened 2024-05-06 07:55 UTC by cservakt

During the storage, the zip files should be stored in one of the report folders instead of `/tmp`. Storing huge zip files can cause storage space saturation in `/tmp`.

`CodeChecker store` would create a new tmp directory in the first given report folder where the zip files can be stored temporarily.

2024-05-06 08:20 UTC, bruntib requested changes

2024-05-06 08:20 UTC, bruntib commented on web/client/codechecker_client/cmd/store.py
> +    temp_dir = "/".join([args.input[0], "tmp"])
Please, use the python pathlib for building file paths so the implementation is more platform independent.

2024-05-06 08:20 UTC, bruntib commented on web/client/codechecker_client/cmd/store.py
> +        if not os.path.exists(temp_dir):
What happens if `temp_dir` already exists?

2024-05-17 09:14 UTC, cservakt commented on web/client/codechecker_client/cmd/store.py
> +        temp_dir = tempfile.mkdtemp(suffix="tmp", dir=args.input[0])
Great idea, much more trackable.

2024-05-17 09:17 UTC, cservakt commented on web/client/codechecker_client/cmd/store.py
> +        os.rmdir(temp_dir)
You are right. The deletion is not recursive in this way. I've already fixed it with using `shutil.rmtree()`

2024-05-21 14:24 UTC, bruntib approved these changes

2024-05-21 14:25 UTC, merged