Analyzer binary dependent environment
Ericsson/codechecker pull request #4305
Opened 2024-07-31 14:55 UTC by dkrupp

If a pre-package analyzer binary (e.g. clang) is found first, the LD_LIBRARY_PATH must be extended. On the other hand, if the analyzer binary is taken from the users machine, the original environment must be used to execute the binary.

This patch introduces an analyzer binary dependent environment initialization.

2024-08-12 23:16 UTC, bruntib requested changes
`SourceAnalyzer` class has a virtual function: `analyze()`. This sets the environment accordingly. The inherited `Gcc` and `Cppcheck` classes override this function which also set the environment. I think, we shouldn't expect the child classes do this job. The `analyze()` functions in these two inherited classes could be removed.

2024-08-12 23:16 UTC, bruntib commented on analyzer/codechecker_analyzer/analyzers/analyzer_types.py
> +                            .get_analyzer_env("clang-apply-replacements"),
```suggestion
                            .get_analyzer_env(
                                os.path.basename(context.replacer_binary)),
```

2024-08-12 23:16 UTC, bruntib commented on analyzer/codechecker_analyzer/analyzers/clangsa/analyzer.py
> +            env=analyzer_context.get_context().get_analyzer_env("clangsa"),
```suggestion
            env=analyzer_context.get_context()\
            .get_analyzer_env(ClangSA.ANALYZER_NAME),
```

2024-08-12 23:16 UTC, bruntib commented on analyzer/codechecker_analyzer/analyzers/clangsa/analyzer.py
> +                analyzer_context.get_context().get_analyzer_env("clangsa"))
```suggestion
                analyzer_context.get_context()\
                .get_analyzer_env(ClangSA.ANALYZER_NAME))
```

2024-08-12 23:16 UTC, bruntib commented on analyzer/codechecker_analyzer/analyzers/clangsa/analyzer.py
> +        environ = context.get_analyzer_env("clangsa")
```suggestion
        environ = context.get_analyzer_env(ClangSA.ANALYZER_NAME)
```

2024-08-12 23:16 UTC, bruntib commented on analyzer/codechecker_analyzer/analyzers/clangtidy/analyzer.py
> +                .get_context().get_analyzer_env("clang-tidy")
```suggestion
                .get_context().get_analyzer_env(cls.ANALYZER_NAME)
```

2024-08-12 23:16 UTC, bruntib commented on analyzer/codechecker_analyzer/analyzers/clangtidy/analyzer.py
> +                .get_analyzer_env("clang-tidy"),
```suggestion
                .get_analyzer_env(cls.ANALYZER_NAME),
```

2024-08-12 23:16 UTC, bruntib commented on analyzer/codechecker_analyzer/analyzers/clangtidy/analyzer.py
> +                .get_analyzer_env("clang-tidy"),
```suggestion
                .get_analyzer_env(cls.ANALYZER_NAME),
```

2024-08-12 23:16 UTC, bruntib commented on analyzer/codechecker_analyzer/analyzers/cppcheck/analyzer.py
> +        check_env = context.get_analyzer_env("cppcheck")
```suggestion
        check_env = context.get_analyzer_env(cls.ANALYZER_NAME)
```

2024-08-14 09:31 UTC, dkrupp commented
> `SourceAnalyzer` class has a virtual function: `analyze()`. This sets the environment accordingly. The inherited `Gcc` and `Cppcheck` classes override this function which also set the environment. I think, we shouldn't expect the child classes do this job. The `analyze()` functions in these two inherited classes could be removed.

Good point! Fixed!

2024-08-14 12:17 UTC, dkrupp commented
Looks like this PR changed the behaviour in CodeChecker:

https://github.com/Ericsson/codechecker/pull/3919/files

the ld_logger.so binary is selected based on the host OS platform instead of the executed binary...

2024-08-14 12:52 UTC, bruntib approved these changes

2024-08-14 12:52 UTC, merged