[cmd] Checker name prefixes are meant along separator characters
Ericsson/codechecker pull request #4311
Opened 2024-08-14 07:10 UTC by bruntib

Checkers can be enabled by groups, e.g. unix.cstring enables all checkers starting with this prefix. However, unix.cs is not a checker group so this shouldn't be allowed. In this case an error message is printed and analysis doesn't start.

2024-08-14 09:50 UTC, dkrupp requested changes
Please add another testcase for testing enabling checker groups.

2024-08-14 09:50 UTC, dkrupp commented on analyzer/tests/unit/test_checker_handling.py
> +        # Enable checkers with a checker group prefix.
this test is enabling one concrete checker alpha.security.ArrayBound and tests that alpha.security.ArrayBoundv2 should not be enabled. It is not testing "checker group prefix"

Could you please add another test case which enables "alpha.security" group. Then alpha.security.ArrayBound and also alpha.security.ArrayBoundv2 should be enabled.

2024-08-14 11:28 UTC, NagyDonat commented
Instead of `alpha.security.ArrayBound` and `alpha.security.ArrayBoundV2`, consider using the checkers `cplusplus.NewDelete` and `cplusplus.NewDeleteLeaks` because their names are more stable. We will hopefully rename/rearrange the bounds checkers within a year, while these are already stable checkers and their names won't change.

2024-08-14 12:45 UTC, bruntib commented
@dkrupp, @NagyDonat Thanks for the comments! I fixed the tests accordingly.

2024-08-15 08:13 UTC, dkrupp approved these changes
LGTM

2024-08-15 08:13 UTC, merged