Revert "[analyzer] Use absolute path to logger.so in LD_PRELOAD"
Ericsson/codechecker pull request #4314
Opened 2024-08-14 16:41 UTC by dkrupp

This reverts commit db924b02424c4ed5fc5c0b21af19c848ad45e6f2.

ld_logger.so binary version (32 or 64 bits) must depend on the excuted builder binary version, not on the host machine platform version.

Fixes #4312

2024-08-15 07:25 UTC, bruntib requested changes
There are some Pylint warnings too, otherwise it looks good.

2024-08-15 07:25 UTC, bruntib commented on analyzer/tools/build-logger/README.md
> +export CC_LOGGER_GCC_LIKE="gcc:g++:clang:clang++:cc:c++"
```suggestion
export CC_LOGGER_GCC_LIKE="gcc:g++:clang:clang++:/cc:c++"
```

2024-08-15 07:25 UTC, bruntib commented on analyzer/tools/build-logger/tests/unit/__init__.py
> +            "CC_LOGGER_GCC_LIKE": "gcc:g++:clang:clang++:cc:c++",
```suggestion
            "CC_LOGGER_GCC_LIKE": "gcc:g++:clang:clang++:/cc:c++",
```

2024-08-15 08:11 UTC, dkrupp commented
thanks for the review. pylint problems also fixed.

2024-08-15 08:35 UTC, bruntib approved these changes

2024-08-15 08:35 UTC, merged

2024-08-23 06:22 UTC, odin- commented
Great :-). Thanks for the fix.