Add clang-tidy yaml report converter
Ericsson/codechecker pull request #4335
Opened 2024-09-02 07:04 UTC by noraz31

Currently clang-tidy reports are parsed and
converted to plist files from the clang-tidy
standard outputs. This change adds a new
report converter that uses clang-tidy's yaml
outputs as inputs for parsing and
creating plist files.

2024-11-06 14:56 UTC, cservakt submitted a review, later dismissed

2024-11-06 14:56 UTC, cservakt commented on tools/report-converter/tests/unit/analyzers/test_clang_tidy_yaml_parser.py
> +            print(res)
Are these prints necessary?

2025-01-15 09:09 UTC, noraz31 commented on tools/report-converter/codechecker_report_converter/analyzers/clang_tidy_yaml/parser.py
> +        file_path = os.path.abspath(diagnostic_message['FilePath'])
It is indeed safer, thanks for the suggestion. In this case, I believe the key will always exist based on the logic, but I’m changing it to get() to handle edge cases more effectively.

2025-01-15 09:15 UTC, noraz31 commented on tools/report-converter/codechecker_report_converter/analyzers/clang_tidy_yaml/parser.py
> +            file_path, diagnostic_message['FileOffset'])
Fixed

2025-01-15 13:34 UTC, noraz31 commented on tools/report-converter/codechecker_report_converter/analyzers/clang_tidy_yaml/parser.py
> +        file_path = os.path.abspath(diagnostic_message['FilePath'])
Fixed

2025-01-15 13:35 UTC, noraz31 commented on tools/report-converter/codechecker_report_converter/analyzers/clang_tidy_yaml/parser.py
> +            file_path, diagnostic_message['FileOffset'])
Fixed

2025-01-15 13:35 UTC, noraz31 commented on tools/report-converter/codechecker_report_converter/analyzers/clang_tidy_yaml/parser.py
> +            message=diagnostic_message['Message'].strip(),
Fixed

2025-01-15 13:35 UTC, noraz31 commented on tools/report-converter/tests/unit/analyzers/test_clang_tidy_yaml_parser.py
> +            print(res)
Fixed

2025-01-24 10:22 UTC, dkrupp requested changes
Create a concrete test case which shows an example where the hash will be different than the original clang-tidy stdout converter

2025-01-28 19:03 UTC, noraz31 commented
> Create a concrete test case which shows an example where the hash will be different than the original clang-tidy stdout converter

Looks like this issue occurred earlier due to some differences in filenames/file paths. Unified clang-tidy & clang-tidy-yaml test case no. 3 and added test case no. 7 for both report converters to demonstrate this. The tests were made using the same build directory and filename, and the output files contain the same hashes.

2025-01-29 11:36 UTC, bruntib approved these changes

2025-01-29 12:39 UTC, merged