[analyzer] Include arch subdirectories in LD_LIBRARY_PATH for logging
Ericsson/codechecker pull request #4394
Opened 2024-12-02 19:54 UTC by gamesh411

2024-12-02 20:19 UTC, gamesh411 commented
The issue with logging (see #4360 for details) came up on my Ubuntu24 machine, where only specifying the `<data_files>/ldlogger/lib` in the LD_LIBRARY_PATH was not enough for the dynamic loader to load the `ldlogger.so` inside  `<data_files>/ldlogger/lib/x86_64`, so I observed there is no implicit architecture resolution in the logic of the loader. There were other tests on other distributions where this implicit architecture resolution seems to exist (rhel7, rhel8, ubuntu22, among others).

The solution implemented by this patch is adding all `<data_files>/ldlogger/lib/*` folders in addition to the current ` <data_files>/ldlogger/lib` folder.

I have tested it on Ubuntu24, and the multiple .so files that are possibly reachable due to all of them being added are not an issue. The logger works as expected, and if I remove only the relevant `ldlogger.so` (x86_64 for my machine) but keep the others, the CodeChecker log command correctly detects that I meet neither the ld-logger nor the intercept-build requirement.

2024-12-03 08:38 UTC, dkrupp commented
sounds good. did you test this on older distros? (ubuntu 20, 22,rhel8,rhel9)

2024-12-05 12:47 UTC, dkrupp commented
You may want to try out this implmentation on the following test

test.c:
```
int main(void){
  return 0;
}
```

builder.c:
```
#include<stdlib.h>
int main(void){
  const char* command="gcc ./test.c";
  system(command);
  return 0;
}
```
`gcc -m32 ./builder.c -o builder32`



`CodeChecker log -b ./builder32 -o compile_command32.json`

2024-12-05 14:05 UTC, gamesh411 commented
Hi, I have tested with the suggested method, and both logs have the correct content.
I tested the above approach but modified the builder to make it even more convoluted like this:

```
#include<stdlib.h>
int main(void) {
  system("/path/to/32bitcompiler/bin/clang -o test_build_with_clang32 test.c");
  system("/path/to/64bitcompiler/bin/clang -o test_build_with_clang64 test.c");
  return 0;
}
```
Then, build this to `builder32` and `builder64`, and log them like this:
```
strace -fte trace=%process,%file CodeChecker log -b './builder32' -o ccdb32.json 2>&1 | tee strace_log32
strace -fte trace=%process,%file CodeChecker log -b './builder64' -o ccdb64.json 2>&1 | tee strace_log64
```
Then, the contents of *BOTH* `ccdb32.json` and `ccdb64.json`: 
```
[
	{
		"directory": "...",
		"command": "/path/to/32bitcompiler/bin/clang -o test_build_with_clang32 test.c",
		"file": "test.c"
	}
	,
	{
		"directory": "...",
		"command": "/path/to/64bitcompiler/bin/clang -o test_build_with_clang64 test.c",
		"file": "test.c"
	}
]
```
All in all, I see this is the expected behaviour.

2024-12-05 15:31 UTC, dkrupp requested changes
I like the proposed solution and I tested and it works on ubuntu 22 too
I think we can remove the i486, i586, i686 subdirs of ld_logger/lib
and just keep i386 dir.

Also could you please add the testcase which I proposed in my comment as functional test?

2024-12-05 15:31 UTC, dkrupp commented on analyzer/codechecker_analyzer/analyzer_context.py
> +            [str(ld_logger_path)] +
I think we dont need to add CodeChecker/ld_logger/lib/
and then we can also remove the  'i486' 'i586' 'i686' subdirectories from analyzer/tools/build-logger/Makefile line 79
`  for x86dir in 'i386' 'i486' 'i586' 'i686'; do \`

2024-12-06 18:21 UTC, gamesh411 commented
@dkrupp Thanks for the suggestions. I implemented and verified all of them on Ubuntu24 and this Ubuntu20 test environment.

2024-12-10 11:04 UTC, merged